# Generated by Django 2.2.4 on 2021-05-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dispatcher',
        ),
    ]
