# Generated by Django 2.2.4 on 2021-05-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_partnerstore_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='attr',
        ),
    ]
