# Generated by Django 2.2.4 on 2021-05-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_item_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attr',
            field=models.ManyToManyField(to='core.AttValue'),
        ),
        migrations.AddField(
            model_name='partnerstore',
            name='attribute',
            field=models.ManyToManyField(to='core.AttValue'),
        ),
    ]
