# Generated by Django 2.2.4 on 2021-05-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210520_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attvalue',
            name='status',
        ),
        migrations.AddField(
            model_name='attvalue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
