# Generated by Django 2.2.4 on 2021-05-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210520_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerstore',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
