# Generated by Django 2.2.4 on 2021-05-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210520_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attvalue',
            old_name='attr',
            new_name='attribute',
        ),
    ]
