# Generated by Django 2.2.4 on 2021-05-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210520_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='attr',
            new_name='attribute',
        ),
    ]
