# Generated by Django 2.2.4 on 2021-05-20 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210520_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='attribute',
        ),
        migrations.AddField(
            model_name='item',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Attribute'),
        ),
    ]
