# Generated by Django 2.2.4 on 2021-05-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210520_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='attribute',
        ),
        migrations.AddField(
            model_name='item',
            name='attribute',
            field=models.ManyToManyField(to='core.AttValue'),
        ),
    ]
