# Generated by Django 2.2.4 on 2021-05-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210520_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerstore',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
    ]
