# Generated by Django 2.2.4 on 2021-05-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_menucategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
