# Generated by Django 2.2.4 on 2021-05-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_menucategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerstore',
            name='attribute',
        ),
        migrations.AlterField(
            model_name='item',
            name='attribute',
            field=models.ManyToManyField(to='core.Attribute'),
        ),
    ]
