# Generated by Django 2.2.4 on 2021-05-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210520_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
