# Generated by Django 2.2.4 on 2021-05-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210520_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttValue',
        ),
    ]
