# Generated by Django 2.2.4 on 2021-05-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_delete_attvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='value',
        ),
    ]
