# Generated by Django 2.2.4 on 2021-05-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_attribute_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
