# Generated by Django 2.2.4 on 2021-05-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210521_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=7.446954, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=125.809437, max_digits=10, null=True),
        ),
    ]
