# Generated by Django 2.2.4 on 2021-05-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20210521_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='menu_category',
        ),
        migrations.AddField(
            model_name='item',
            name='menu_category',
            field=models.ManyToManyField(to='core.MenuCategory'),
        ),
    ]
