# Generated by Django 2.2.4 on 2021-05-20 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20210521_0559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
