# Generated by Django 2.2.4 on 2021-05-20 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_menucategory_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='menu_item',
        ),
    ]
