# Generated by Django 2.2.4 on 2021-05-21 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_menucategory_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='menu_category',
        ),
    ]
