# Generated by Django 2.2.4 on 2021-05-21 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_item_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.MenuCategory'),
        ),
    ]
