# Generated by Django 2.2.4 on 2021-05-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20210521_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
