# Generated by Django 2.2.4 on 2021-05-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_item_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
